### ISSUE TITLE
Launch clamps give incoherent warp behaviour message

### ISSUE THREAD

**Issue by Standecco** [Standecco/ROKerbalism#25]
This is just a reminder; the fix should be a simple EC generator module, but boiloff of cryogenics might prove problematic.

**Comment by lpgagnon** [comment]
life support resources for crewed vessels may also need to be handled

**Comment by Standecco** [comment]
should be fixed by a73216f15c55f3a0cb25dec2d9fc903a6b039db6, but needs confirmation; @lpgagnon could you check?

**Comment by lpgagnon** [comment]
Uncrewed vessels seem fine now; crewed vessels still have the problem. To be expected, since the fix only deals with EC

**Comment by Standecco** [comment]
Definitely fixed now
